#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo 'Checking if commit message format follow https://www.conventionalcommits.org/en/v1.0.0/'
yarn commitlint --config=.tooling/.commitlint/commitlint.config.cjs --edit $1
